from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

# MODE
MODE = "DEVELOPMENT"

# Close all open positions and orders
ABORT_ALL_POSITIONS = False

# Find Cointegrated pairs
FIND_COINTEGRATED = True

# Place Trades
PLACE_TRADES = True

# Resolutions 

RESOLUTION = "1HOUR"

# Stats Window
WINDOW = 21

# Thresholds - Opening 
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1880

# Thresholds - Closing
CLOSE_AT_ZSCORE_CROSS = True

#ETH Address
ETHEREUM_ADDRESS = "0x8F9AC93994EA306e907b67281A3909F2295Ef20f"

# KEYS - Development
# Must be on Testnet
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# Keys - Export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_TESTNET

# HOST - Export
HOST = API_HOST_GOERLI

#H HTTP PROVIDER
HTTP_PROVIDER = "https://eth-goerli.g.alchemy.com/v2/CdCR7Y9WAAhKAM0D7tuNd0bT9DA5EdhW"